apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  # echo -n 'cdpi_network_user' | base64
  username: Y2RwaV9uZXR3b3JrX3VzZXI=
  # echo -n 'CHANGEZ_CE_MOT_DE_PASSE' | base64
  password: Q0hBTkdFWl9DRV9NT1RfREVfUEFTU0U=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  # echo -n 'CHANGEZ_CETTE_CLE_JWT_SECRETE' | base64
  jwt-secret: Q0hBTkdFWl9DRVRUEV9DTEVFX0pXVF9TRUNSRVRF
---
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: default
type: Opaque
data:
  # echo -n 'your_smtp_user' | base64
  smtp-user: eW91cl9zbXRwX3VzZXI=
  # echo -n 'your_smtp_password' | base64
  smtp-password: eW91cl9zbXRwX3Bhc3N3b3Jk